### ISSUE TITLE
Crafting Recipes

### ISSUE THREAD

**Issue by Vequinox** [TeamMetallurgy/Metallurgy6#5]
- [x] "Vanilla" Tools

- [x] Iron and Steel rods (with forge tags)

- [x] Need art for Iron rod and Steel rod

Update as needed

**Comment by Vequinox** [comment]
@Shadowclaimer I remember you discussed something about some of the tool recipes requiring a different thing than a regular stick for the base. Is that true, or am I just misremembering? I'm trying to generate the recipes for the tools currently.

**Comment by Shadowclaimer** [comment]
Damascus Steel, Heavy Steel, Manganese Steel, Nickel Steel, Fungal Steel, Meteor Steel, Corinthian Steel, Shimmer Steel, all require Iron Rods.

Woven Steel and Pure Steel require a Steel Rod (made from any steel)

**Comment by Vequinox** [comment]
> Damascus Steel, Heavy Steel, Manganese Steel, Nickel Steel, Fungal Steel, Meteor Steel, Corinthian Steel, Shimmer Steel, all require Iron Rods.
> 
> Woven Steel and Pure Steel require a Steel Rod (made from any steel)

Alright, and what will making those rods look like? Just in hand/crafting table crafting or will our machines make those rods? And are they different than the eventual keyworded rods?

**Comment by Shadowclaimer** [comment]
Hand crafting, typical wood rod recipe (but with metal instead of wood)
makes 2 bars instead of 4. I have the artwork I can export.

They are different from our eventual keyworded rods.

So they will be removed once the actual rod system is added.

**Comment by Vequinox** [comment]
Ah ok, so vanilla tools are only for the alpha build? Then when we get keywording in place for tool head + rod crafting, we do away with the vanilla tools?

**Comment by Shadowclaimer** [comment]
Correct.

**Comment by Vequinox** [comment]
In the M6 google spreadsheet, you have all the steels as counting as "Steel" in the ore dictionary besides Woven Steel. Is that on purpose or accident?

**Comment by Shadowclaimer** [comment]
Just updated it, King's Steel and Corinthian Steel should've been steels as
well.

Yes Pure Steel and Woven Steel are not considered Steels for forge
dictionary use or for making rods.

>
